{{- if and .Values.istio.enabled .Values.istio.destinationRule.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ include "go-app.fullname" . }}
  labels:
    {{- include "go-app.labels" . | nindent 4 }}
spec:
  host: {{ include "go-app.fullname" . }}
  {{- with .Values.istio.destinationRule.trafficPolicy }}
  trafficPolicy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
