{{- if .Values.secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "go-app.fullname" . }}
  labels:
    {{- include "go-app.labels" . | nindent 4 }}
type: Opaque
data:
  {{- toYaml .Values.secrets.data | nindent 2 }}
{{- end }}
